set(headers ${headers}
	include/Cache.h
	include/Data/BaseFilters.h
	include/Data/EnumDefs.h
	include/Data/FormData.h
	include/Data/ItemData.h
	include/Data/Ranges.h
	include/Data/Traits.h
	include/Defs.h
	include/DependencyResolver.h
	include/Distribute.h
	include/ExclusiveGroups.h
	include/Hooks.h
	include/KeywordData.h
	include/KeywordDependencies.h
	include/LogBuffer.h
	include/LookupConfigs.h
	include/LookupForms.h
	include/PCH.h
	include/RE.h
	include/Settings.h
)
